import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderWithSession from "./_components/HeaderWithSession";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Basket Court Map",
  description: "Generated by create next app",
  // アイコンの設定
  icons: {
    icon: "/images/BasketGoal_Icon.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${inter.className} flex flex-col h-screen`}>
        <HeaderWithSession />
        {children}
        <Footer />
      </body>
    </html>
  );
}
